---
apiVersion: v1
kind: Service
metadata:
  name: docker
spec:
  type: LoadBalancer
  selector:
    app: docker
  ports:
  - port: 3000
    targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: docker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docker
  template:
    metadata:
      labels:
        app: docker
    spec:
      containers:
      - name: docker
        image: europe-central2-docker.pkg.dev/GCP_PROJECT_ID/infrastructure-test/docker:latest