name: Build, Push, and Deploy to GKE

on:
  push:
    branches:
    - 'master'

env:
  REGION: europe-central2

jobs:
  deploy:
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: ubuntu-latest
    steps:

    - name: code checkout
      uses: actions/checkout@v2

    - uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GCP_APPLICATION_CREDENTIALS }}'

    - name: Login to GAR
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGION }}-docker.pkg.dev
        username: _json_key
        password: ${{ secrets.GCP_APPLICATION_CREDENTIALS }}
    

    - name: install the gcloud cli
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_APPLICATION_CREDENTIALS }}
        install_components: 'gke-gcloud-auth-plugin'
        export_default_credentials: true

    - name: build and push the docker image
      env:
        GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      run: |
        gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev
        docker build -t ${{ env.REGION }}-docker.pkg.dev/$GCP_PROJECT_ID/infrastructure-test/docker:latest ./application
        docker push ${{ env.REGION }}-docker.pkg.dev/$GCP_PROJECT_ID/infrastructure-test/docker:latest

        
    - name: deploy to gke
      env:
        GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      run: |
        gcloud container clusters get-credentials autopilot-cluster-1 --region ${{ env.REGION }}
        sed -i "s/GCP_PROJECT_ID/$GCP_PROJECT_ID/g" ./kubernetes/resources.yaml
        kubectl apply -f ./kubernetes/resources.yaml