name: Build, Push, and Deploy to GKE

on:
  push:
    branches:
      - master

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}   # Set up in GitHub Secrets
  CLUSTER_NAME: ${{ secrets.GKE_CLUSTER_NAME }}
  GKE_ZONE: ${{ secrets.GKE_ZONE }}
  IMAGE: gcr.io/${{ secrets.GCP_PROJECT_ID }}/typescript-app:latest

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Configure Docker to use gcloud as a credential helper
        run: gcloud auth configure-docker

      - name: Install dependencies and build TypeScript app
        working-directory: ./appplication/
        run: |
          npm install
          npm run build

      - name: Build Docker image
        working-directory: ./appplication/
        run: docker build -t $IMAGE .

      - name: Push Docker image to Google Artifact Registry
        working-directory: ./appplication/
        run: docker push $IMAGE

      - name: Get GKE cluster credentials
        run: gcloud container clusters get-credentials $CLUSTER_NAME --zone $GKE_ZONE --project $PROJECT_ID

      - name: Deploy to GKE
        run: |
          kubectl set image deployment/my-app-deployment my-app-container=$IMAGE --record
